#ifndef _BSP_STEPMOTOR_H_
#define _BSP_STEPMOTOR_H

#define RCC_STEPMOTOR1_EN 	 (RCC_AHB1Periph_GPIOC | RCC_AHB1Periph_GPIOB)
#define GPIO_PORT_STEPMOTOR1_EN      GPIOC
#define GPIO_PIN_STEPMOTOR1_EN	 GPIO_Pin_4
#define GPIO_PORT_STEPMOTOR1_DIR      GPIOC
#define GPIO_PIN_STEPMOTOR1_DIR	 GPIO_Pin_5
#define GPIO_PORT_STEPMOTOR1_CP      GPIOB
#define GPIO_PIN_STEPMOTOR1_CP	 GPIO_Pin_0

#define RCC_STEPMOTOR2_EN 	 (RCC_AHB1Periph_GPIOE)
#define GPIO_PORT_STEPMOTOR2_EN      GPIOE
#define GPIO_PIN_STEPMOTOR2_EN	 GPIO_Pin_9
#define GPIO_PORT_STEPMOTOR2_DIR      GPIOE
#define GPIO_PIN_STEPMOTOR2_DIR	 GPIO_Pin_10
#define GPIO_PORT_STEPMOTOR2_CP      GPIOE
#define GPIO_PIN_STEPMOTOR2_CP	 GPIO_Pin_11

#define RCC_STEPMOTOR3_EN 	 (RCC_AHB1Periph_GPIOE)
#define GPIO_PORT_STEPMOTOR3_EN      GPIOE
#define GPIO_PIN_STEPMOTOR3_EN	 GPIO_Pin_12
#define GPIO_PORT_STEPMOTOR3_DIR      GPIOE
#define GPIO_PIN_STEPMOTOR3_DIR	 GPIO_Pin_13
#define GPIO_PORT_STEPMOTOR3_CP      GPIOE
#define GPIO_PIN_STEPMOTOR3_CP	 GPIO_Pin_14

#define STEPMOTOR3_EN_H()     GPIO_SetBits(GPIO_PORT_STEPMOTOR3_EN,GPIO_PIN_STEPMOTOR3_EN)
#define STEPMOTOR3_EN_L()     GPIO_ResetBits(GPIO_PORT_STEPMOTOR3_EN,GPIO_PIN_STEPMOTOR3_EN)

#define STEPMOTOR1_DIR_H()     GPIO_SetBits(GPIO_PORT_STEPMOTOR1_DIR,GPIO_PIN_STEPMOTOR1_DIR)
#define STEPMOTOR1_DIR_L()     GPIO_ResetBits(GPIO_PORT_STEPMOTOR1_DIR,GPIO_PIN_STEPMOTOR1_DIR)

#define STEPMOTOR2_DIR_H()     GPIO_SetBits(GPIO_PORT_STEPMOTOR2_DIR,GPIO_PIN_STEPMOTOR2_DIR)
#define STEPMOTOR2_DIR_L()     GPIO_ResetBits(GPIO_PORT_STEPMOTOR2_DIR,GPIO_PIN_STEPMOTOR2_DIR)

#define STEPMOTOR3_DIR_H()     GPIO_SetBits(GPIO_PORT_STEPMOTOR3_DIR,GPIO_PIN_STEPMOTOR3_DIR)
#define STEPMOTOR3_DIR_L()     GPIO_ResetBits(GPIO_PORT_STEPMOTOR3_DIR,GPIO_PIN_STEPMOTOR3_DIR)

#define STEPMOTOR1      1
#define STEPMOTOR2      2

void bsp_InitStepMotor(void);
void TIM3_PWM_SETPMOTOR(void);
void TIM1_PWM_SETPMOTOR(void);
void StepMotor_adjust_speed(u8 motor,u32 value);
void TIM8_PWM_SETPMOTOR(void);
#endif