#ifndef _BSP_SERVOMOTOR_H_
#define _BSP_SERVOMOTOR_H

#define RCC_SERVOMOTOR 	 (RCC_AHB1Periph_GPIOB | RCC_AHB1Periph_GPIOD)

#define GPIO_PORT_SERVOMOTOR1      GPIOB
#define GPIO_PIN_SERVOMOTOR1	 GPIO_Pin_14

#define GPIO_PORT_SERVOMOTOR2      GPIOD
#define GPIO_PIN_SERVOMOTOR2	 GPIO_Pin_12

#define GPIO_PORT_SERVOMOTOR3      GPIOD
#define GPIO_PIN_SERVOMOTOR3	 GPIO_Pin_15

#define GPIO_PORT_SERVOMOTOR4      GPIOD
#define GPIO_PIN_SERVOMOTOR4	 GPIO_Pin_13

#define GPIO_PORT_SERVOMOTOR_G      GPIOB
#define GPIO_PIN_SERVOMOTOR_G	 GPIO_Pin_15

#define GPIO_PORT_SERVOMOTOR_G0      GPIOD
#define GPIO_PIN_SERVOMOTOR_G0	 GPIO_Pin_14

void bsp_InitServoMotor(void);
void TIM12_PWM_SERVOMOTOR(void);
void TIM4_PWM_SERVOMOTOR(void);
#endif